// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: eventcore/v1/utilizedtransportequipment.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UtilizedTransportEquipmentService_CreateUtilizedTransportEquipment_FullMethodName = "/eventcore.v1.UtilizedTransportEquipmentService/CreateUtilizedTransportEquipment"
)

// UtilizedTransportEquipmentServiceClient is the client API for UtilizedTransportEquipmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The UtilizedTransportEquipmentService service definition.
type UtilizedTransportEquipmentServiceClient interface {
	CreateUtilizedTransportEquipment(ctx context.Context, in *CreateUtilizedTransportEquipmentRequest, opts ...grpc.CallOption) (*CreateUtilizedTransportEquipmentResponse, error)
}

type utilizedTransportEquipmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUtilizedTransportEquipmentServiceClient(cc grpc.ClientConnInterface) UtilizedTransportEquipmentServiceClient {
	return &utilizedTransportEquipmentServiceClient{cc}
}

func (c *utilizedTransportEquipmentServiceClient) CreateUtilizedTransportEquipment(ctx context.Context, in *CreateUtilizedTransportEquipmentRequest, opts ...grpc.CallOption) (*CreateUtilizedTransportEquipmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUtilizedTransportEquipmentResponse)
	err := c.cc.Invoke(ctx, UtilizedTransportEquipmentService_CreateUtilizedTransportEquipment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UtilizedTransportEquipmentServiceServer is the server API for UtilizedTransportEquipmentService service.
// All implementations must embed UnimplementedUtilizedTransportEquipmentServiceServer
// for forward compatibility.
//
// The UtilizedTransportEquipmentService service definition.
type UtilizedTransportEquipmentServiceServer interface {
	CreateUtilizedTransportEquipment(context.Context, *CreateUtilizedTransportEquipmentRequest) (*CreateUtilizedTransportEquipmentResponse, error)
	mustEmbedUnimplementedUtilizedTransportEquipmentServiceServer()
}

// UnimplementedUtilizedTransportEquipmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUtilizedTransportEquipmentServiceServer struct{}

func (UnimplementedUtilizedTransportEquipmentServiceServer) CreateUtilizedTransportEquipment(context.Context, *CreateUtilizedTransportEquipmentRequest) (*CreateUtilizedTransportEquipmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUtilizedTransportEquipment not implemented")
}
func (UnimplementedUtilizedTransportEquipmentServiceServer) mustEmbedUnimplementedUtilizedTransportEquipmentServiceServer() {
}
func (UnimplementedUtilizedTransportEquipmentServiceServer) testEmbeddedByValue() {}

// UnsafeUtilizedTransportEquipmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UtilizedTransportEquipmentServiceServer will
// result in compilation errors.
type UnsafeUtilizedTransportEquipmentServiceServer interface {
	mustEmbedUnimplementedUtilizedTransportEquipmentServiceServer()
}

func RegisterUtilizedTransportEquipmentServiceServer(s grpc.ServiceRegistrar, srv UtilizedTransportEquipmentServiceServer) {
	// If the following call pancis, it indicates UnimplementedUtilizedTransportEquipmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UtilizedTransportEquipmentService_ServiceDesc, srv)
}

func _UtilizedTransportEquipmentService_CreateUtilizedTransportEquipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUtilizedTransportEquipmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UtilizedTransportEquipmentServiceServer).CreateUtilizedTransportEquipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UtilizedTransportEquipmentService_CreateUtilizedTransportEquipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UtilizedTransportEquipmentServiceServer).CreateUtilizedTransportEquipment(ctx, req.(*CreateUtilizedTransportEquipmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UtilizedTransportEquipmentService_ServiceDesc is the grpc.ServiceDesc for UtilizedTransportEquipmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UtilizedTransportEquipmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eventcore.v1.UtilizedTransportEquipmentService",
	HandlerType: (*UtilizedTransportEquipmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUtilizedTransportEquipment",
			Handler:    _UtilizedTransportEquipmentService_CreateUtilizedTransportEquipment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eventcore/v1/utilizedtransportequipment.proto",
}
